# Config options for phase 1: training multi-subject head only
encoder: grouplin
trunk:
layers:
  - backbone.stages.0
  - backbone.stages.1
  - backbone.stages.2
  - backbone.stages.3
embed_state: /root/autodl-tmp/code/43.algonauts23-CC/weights/group_pca_d-4096.pt
proj_dim: 4096
hidden_dim: 1024
epochs: 40
batch_size: 64
lr: 6.0e-4
weight_decay: 0.8
dropout: 0.9
crop_scale: 0.8
min_lr_fraction: 0.05
amp: true
